# Generated by Django 5.0.4 on 2024-04-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
