# Generated by Django 5.0.4 on 2024-04-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_registry', '0003_remove_function_entry_point_function_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('node', 'Node')], max_length=50),
        ),
    ]
