# Generated by Django 5.0.4 on 2024-04-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_registry', '0004_alter_function_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='language',
            field=models.CharField(choices=[('python', 'Python')], max_length=50),
        ),
    ]
