# Generated by Django 5.0.4 on 2024-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_point', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('memory_limit', models.IntegerField(default=128)),
                ('cpu_limit', models.IntegerField(default=5000)),
                ('timeout', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
