# Generated by Django 5.0.4 on 2024-04-12 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_registry', '0002_alter_function_name'),
        ('trigger_registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='functions',
        ),
        migrations.AddField(
            model_name='trigger',
            name='function',
            field=models.ForeignKey(default='23', on_delete=django.db.models.deletion.CASCADE, to='function_registry.function'),
            preserve_default=False,
        ),
    ]
